# Generated by Django 5.1 on 2024-08-13 19:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=ckeditor.fields.RichTextField(blank=True, max_length=2500, null=True),
        ),
    ]
