# Generated by Django 5.1 on 2024-08-10 23:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
